"""create initial tables

Revision ID: 3de7fb8d67ec
Revises: a1b2c3d4e5f6
Create Date: 2026-03-23 11:55:40.002753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de7fb8d67ec'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_student',
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guardian_id', 'student_id')
    )
    op.drop_table('guardian_students')
    op.alter_column('occurrences', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('occurrences', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.
"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('occurrences', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('occurrences', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_table('guardian_students',
    sa.Column('guardian_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], name=op.f('guardian_students_guardian_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('guardian_students_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guardian_id', 'student_id', name=op.f('guardian_students_pkey'))
    )
    op.drop_table('guardian_student')
    # ### end Alembic commands ###
