"""Adicionar tabela classrooms e FK classroom_id em users

Revision ID: 5b98d86b99c7
Revises: b4d500355699
Create Date: 2026-03-20 20:59:21.798244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b98d86b99c7'
down_revision: Union[str, Sequence[str], None] = 'b4d500355699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
    'fk_users_classroom_id',
    'users',
    'classrooms',
    ['classroom_id'],
    ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_classroom_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'classroom_id')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
