"""add rbac system to users

Revision ID: 924749d81359
Revises: 79bd589ece1b
Create Date: 2026-03-09 10:07:50.687872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924749d81359'
down_revision: Union[str, Sequence[str], None] = '79bd589ece1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userrole AS ENUM ('student', 'guardian', 'teacher', 'coordinator', 'porter', 'admin')")
    
    op.add_column('users', sa.Column('role', sa.Enum('STUDENT', 'GUARDIAN', 'TEACHER', 'COORDINATOR', 'PORTER', 'ADMIN', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('is_tutor', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_tutor')
    op.drop_column('users', 'role')

    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
