"""create initial tables with rbac

Revision ID: b4d500355699
Revises: 
Create Date: 2026-03-15 23:13:12.912892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d500355699'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('student', 'guardian', 'teacher', 'coordinator', 'porter', 'admin', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('is_tutor', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.
"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_tutor')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
