"""add schedules

Revision ID: d1596f76447a
Revises: 071ddbdaffde
Create Date: 2026-04-02 16:36:01.860483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1596f76447a'
down_revision: Union[str, Sequence[str], None] = '071ddbdaffde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('affects_all', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('override_classrooms',
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('override_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['override_id'], ['schedule_overrides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classroom_id', 'override_id')
    )
    op.create_table('schedule_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('class_period', 'snack_break', 'lunch_break', name='period_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Enum('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='weekday'), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'weekday', 'period_number', 'type', name='uq_classroom_weekday_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.
"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_slots')
    op.drop_table('override_classrooms')
    op.drop_table('schedule_overrides')
    # ### end Alembic commands ###
